### ISSUE TITLE
VS support

### ISSUE THREAD

**Issue by hhirsch** [GlPortal/glPortal#104]
These are some preserved patches
https://patch-diff.githubusercontent.com/raw/GlPortal/RadixEngine/pull/112.patch
https://patch-diff.githubusercontent.com/raw/GlPortal/glPortal/pull/103.patch
https://patch-diff.githubusercontent.com/raw/GlPortal/glportal-data/pull/12.patch

**Comment by kungfooman** [comment]
I just couldn't see a solution which would fit every plattform yesterday and so the last PR was in end effect pointless.

E.g. I didn't wanna add the sources of all dependencies for Windows developers, when most linux distributions got a well maintained package system. Nor I wanna depend on third party tools to get things rollin (cmake, vcpkg, whatever). Every extra step of work (like installing cmake-gui and use it correctly, for untrained developers) is chopping the percentage of developers who will give it a try. There are epic C/C++ developers, but all the extra stuff like cmake and git are unknown worlds to them. Download the source and open it in Visual Studio. KISS principle.

So I currently just realized that an extra solution for VS is solving all problems, like @hhirsch and @ElementW suggested in the first place iirc.

1) Add all deps as source and no linux dev gives a fuck, since they won't need to pull it
2) The glportal-vs repo will contain all deps, hence I can simply rename the folders, so the include paths can stay the same
3) All the dependencies can be recompiled from source, it is easy to set all kinds of settings, debug/release, 32bit/64bit and not having to worry about incompatible .lib's from third party tools
4) Allows to quickly hack into bullet e.g. to test custom physics stuff and set breakpoints in bullet etc.
5) No need to ship an extra .zip with the dependencies and keeping that updated

**Comment by wow2006** [comment]
I suggest [ExternalProject](https://cmake.org/cmake/help/v3.1/module/ExternalProject.html) which will download prebuilt binaries for windows. This way we don't need external visual studio solution file to update every time we add new files.

**Comment by hhirsch** [comment]
Herman has this covered.
