### ISSUE TITLE
Online multiplayer

### ISSUE THREAD

**Issue by brylie** [GlPortal/glPortal#129]
It would be really cool to work through some glPortal levels/puzzles with a friend. E.g. some puzzles could be designed so that two players need to work together to solve them. What are some ideas/tasks related to providing online multiplayer support for glPortal?

**Comment by hhirsch** [comment]
@brylie I agree. Multiplayer is a great feature. We are currently working on some very basic single player issues. I project multiplayer far into the future because there is still so much work to be done in the single player and we don't have a lot of resources.
In the past I was approached by network devs and if anybody approaches me for network support I'd happily have him work on it. However before it is viable there is still some groundwork to be done in single player. 

The campaign we are currently planning is single player only. But as the engine grows there are probably more campaigns coming. 

Thanks a lot for your interest in the project. If you want to spread the word about the game and engine it is very much appreciated. Who knows. Maybe someone you tell about it will be able to implement multi-player at one point.

**Comment by brylie** [comment]
Out of curiosity, why build a bespoke game engine? Might it be worth the effort to port glPortal to an existing game engine, such as [Godot 3](https://godotengine.org/)?

**Comment by hhirsch** [comment]
@brylie First of all because that is what I found when I first forked the project. It is also a fun and educational exercise. Since we don't have a deadline we can experiment and research to our hearts contend. There are plenty of faster ways to get a game done. But I don't want to put that kind of pressure on me in my free time. I am very interested in what makes a game engines tick and coding from the ground up is a great learning opportunity.

You can continue commenting on this issue and we also have a subreddit that you can ask questions on https://www.reddit.com/r/RadixEngine/

You can also reach me on freenode in #glportal and through the chat on glportal.de.
If you tell me your E-Mail address I'll invite you to our internal slack channel.
I will respond on twitter @glportal_game.

I am glad you are interested in what we are doing and I am looking forward to answer more questions.
Keep the suggestions/issues coming.

**Comment by brylie** [comment]
My email is brylie@gnumedia.org
